use codeup_test_db;

insert into albums (artists, name, release_date, sales, genre) values ("Michael Jackson", "Thriller", 1976, 66, "Pop, rock, R&B"),
("Eagles", "Thei Greates Hits", 1976, 51, "Country rock, soft rock, folk rock"),
("AC/DC", "Back in Black", 1980, 50, "Hard rock"),
("Pink Floyd", "The Dark Side Of The Moon", 1973, 45, "Progressive rock"),
("Whitney Houston", "The Bodyguard", 1992, 45, "R&B, soul, pop, soundtrack"),
("Meat Loaf", "Bat Out of Hell", 1977, 43, "Hard rock, glam rock, heavy metal"),
("Eagles", "Hotel California", 1976, 42, "Soft rock"),
("Bee Gees", "Saturday Night Fever", 1977, 40, "Disco"),
("Fleetwood Mac", "Rumours", 1977, 40, "Soft rock"),
("Shania Twain", "Come On Over", 1997, 40, "Country, pop"),
("Various artists", "Grease: The Original Soundtrack from the Motion Picture", 1978, 38, "Rock and roll"),
("Led Zeppelin", "Led Zeppelin IV", 1971,38, "Hard rock, heavy metal, folk rock"),
("Michael Jackson", "Bad", 1987, 35, "Pop, funk, rock"),
("Alains Morissette", "Jagged Little Pill", 1995, 33, "Alternative rock"),
("Celine Dion", "Falling into You", 1996, 32, "Pop, soft rock"),
("The Beatles", "Sgt. Pepper's Lonely Hearts Club Band", 1967, 32, "Rock"),
("Various artists", "Dirty Dancing", 1987, 32, "Pop, rock, R&B"),
("Michael Jackson", "Dangerous", 1991, 32, "Rock, funk, pop"),
("Adele", "21", 2011, 31, "Pop, soul"),
("Celine Dion", "Let's Talk About Love", 1997, 31, "Pop, soft rock"),
("The Beatles", "1", 2000, 31, "Rock"),
("ABBA", "Gold: Greatest Hits", 1992, 30, "Pop, disco"),
("Madonna", "The Immaculate Collection", 1990, 30, "Pop, dance"),
("The Beatles", "Abbey Road", 1969, 30, "Rock"),
("Bruce", "Born in the U.S.A", 1984, "Heartland rock"),
("Dire Straits", "Brothers in Arms", 1985, 30, "Roots rock, blues rock, soft rock"),
("James Horner", "Titanic: Music from the Motion Picture", 1997, 30, "Film score"),
("Metallica", "Metallica", 1991, 31, "Heavy metal"),
("Nirvana", "Nevermind", 1991, 30, "Grunge, alternative rock"),
("Pink Floyd", "The Wall", 1979, 30, "Progressive rock"),
("Santana", "Supernatural", 1999, 30, "Latin rock"),
("Guns N' Roses", "Appetite for Destruction", 1987, 30, "Hard rock");